// <auto-generated />
namespace EFCodeFirst.Test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modified_Id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modified_Id));
        
        string IMigrationMetadata.Id
        {
            get { return "201707101157480_modified_Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
